In [1]:
import pandas as pd, requests, datetime as dt, re
from bs4 import BeautifulSoup
from selenium import webdriver
from time import sleep

In [2]:
url = 'https://truckersedge.dat.com'
response = requests.get(url)
response.status_code

200

In [52]:
element_list = driver.find_elements_by_tag_name('dat-search-result-row')

for item in element_list :
    driver.execute_script("arguments[0].scrollIntoView();", item)

In [3]:
driver = webdriver.Chrome(executable_path="./chromedriver/macos/chromedriver")

In [185]:
soup = BeautifulSoup(driver.page_source, 'lxml')

In [392]:
now = datetime.datetime.now()

In [393]:
prev_length = 0

In [397]:
rows=[]

In [398]:
element_list = driver.find_elements_by_tag_name('dat-search-result-row')

for item in element_list :
    driver.execute_script("arguments[0].scrollIntoView();", item)

In [399]:
soup = BeautifulSoup(driver.page_source, 'lxml')
for tag in soup.find_all('dat-search-result-row'):
    for taga in tag.find_all('div', {'class':'ng-star-inserted'})[0:1]:
        age = taga.text
        length = len(age)
        if length < prev_length-1:
            break
        hr_min = re.split('\D+', age)
        hr = int(hr_min[-3] or 0)
        mi = int(hr_min[-2])
        posted = now - datetime.timedelta(hours=hr, minutes=mi)
        posted = posted.strftime('%H:%M')
    for taga in tag.find_all('a')[0:1]:
        miles = taga.text
    for taga in tag.find_all('span')[3:4]:
        date = taga.text
    for taga in tag.find_all('span')[4:5]:
        origin = taga.text
    for taga in tag.find_all('span')[13:14]:
        dest = taga.text
    for taga in tag.find_all('span')[25:26]:
        weight = taga.text
    for taga in tag.find_all('span')[28:29]:
        shipper = taga.text
        if shipper == 'â€”':
            for taga in tag.find_all('span')[29:30]:
                shipper = taga.text
 
    if length < prev_length-1:
        break
    
#    print(num, age, hr, min, posted, miles, date, origin, dest, weight, shipper[:24])
#    num += 1
    
    row = {'posted': posted, 'miles': miles, 'origin': origin, 'dest': dest, 
            'weight': weight, 'shipper': shipper}
    rows.append(row)
    prev_length = length

In [400]:
len(rows)

0

In [154]:
cols = ['posted', 'miles', 'origin', 'dest', 'weight', 'shipper', 'time']

In [191]:
df = pd.DataFrame(rows, columns=cols)

In [192]:
df.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
11:14,"1,406","City Of Indus,CA","Roanoke,TX","24,000","Arnold Transportation Services Inc, Grand Prai...",NaN
11:11,"1,362","San Diego,CA","Dallas,TX","14,000","Tristar Transit Inc, Sylmar, CA",NaN
11:11,"1,423","City Of Indus,CA","Dallas,TX","42,000","R2 Logistics Inc, Dallas, TX",NaN
11:08,"1,357","Vista,CA","Ft Worth,TX","25,000","Landstar Ranger Inc, San Antonio, TX",NaN
11:06,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
11:04,"1,423","City Of Indus,CA","Dallas,TX","43,900","Fremont Contract Carriers, Fremont, NE",NaN
11:04,"1,462","Shafter,CA","Grand Prairie,TX","45,000","Uber Freight Llc, Chicago, IL",NaN
11:03,"1,527","Eastvale,CA","Mt Pleasant,TX","42,000","Echo Global Logistics Inc, Dallas, TX",NaN
10:53,"1,527","Eastvale,CA","Mt Pleasant,TX","42,000","Echo Global Logistics Inc, Long Beach, CA",NaN
10:25,"1,423","City Of Indus,CA","Dallas,TX","42,000","R2 Logistics Inc, Dallas, TX",NaN
10:23,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
10:06,"1,440","Los Angeles,CA","Dallas,TX","25,000","Total Quality Logistics Inc, Milford, OH",NaN
09:18,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
06:05,"1,433","Santa Fe Spgs,CA","Carrollton,TX","40,000","Fleet Logistics, Portland, OR",NaN
04:57,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
13:59,"1,402","Pico Rivera,CA","Rockwall,TX","6,000","One Point Logistics Inc, Nashville, TN",NaN
13:21,"1,510","Long Beach,CA","Athens,TX","24,000","American Logistics Group Inc, Melville, NY",NaN

In [413]:
df1 = df1[df1['posted']<'13']

In [416]:
df0.shape

(15, 7)

In [420]:
match = ['miles', 'origin', 'dest', 'shipper']

In [421]:
df0[match].head()

,miles,origin,dest,shipper
0,"1,406","City Of Indus,CA","Roanoke,TX","Arnold Transportation Services Inc, Grand Prai..."
1,"1,362","San Diego,CA","Dallas,TX","Tristar Transit Inc, Sylmar, CA"
2,"1,423","City Of Indus,CA","Dallas,TX","R2 Logistics Inc, Dallas, TX"
3,"1,357","Vista,CA","Ft Worth,TX","Landstar Ranger Inc, San Antonio, TX"
4,"1,423","City Of Indus,CA","Dallas,TX","R2 Logistics Inc, Dallas, TX"

In [210]:
df1 = pd.DataFrame(rows, columns=cols)
df1.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
11:48,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
11:48,"1,362","San Diego,CA","Dallas,TX","14,000","Tristar Transit Inc, Sylmar, CA",NaN
11:41,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
11:35,"1,406","City Of Indus,CA","Roanoke,TX","10,000","Arnold Transportation Services Inc, Grand Prai...",NaN
11:33,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
11:33,"1,380","San Diego,CA","Allen,TX",â€”,"CH Robinson Company, Overland Park, KS",NaN
11:31,"1,423","City Of Indus,CA","Dallas,TX","42,000","R2 Logistics Inc, Dallas, TX",NaN
11:09,"1,462","Shafter,CA","Grand Prairie,TX","45,000","Uber Freight Llc, Chicago, IL",NaN
11:08,"1,527","Eastvale,CA","Mt Pleasant,TX","42,000","Echo Global Logistics Inc, Dallas, TX",NaN
10:58,"1,527","Eastvale,CA","Mt Pleasant,TX","42,000","Echo Global Logistics Inc, Long Beach, CA",NaN
10:30,"1,423","City Of Indus,CA","Dallas,TX","42,000","R2 Logistics Inc, Dallas, TX",NaN
06:10,"1,433","Santa Fe Spgs,CA","Carrollton,TX","40,000","Fleet Logistics, Portland, OR",NaN
05:02,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
14:04,"1,402","Pico Rivera,CA","Rockwall,TX","6,000","One Point Logistics Inc, Nashville, TN",NaN
13:26,"1,510","Long Beach,CA","Athens,TX","24,000","American Logistics Group Inc, Melville, NY",NaN

In [217]:
df2 = pd.DataFrame(rows, columns=cols)
df2.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
14:00,"1,438","Carson,CA","Irving,TX","30,000","Landstar Ranger Inc, Tampa, FL",NaN
13:59,"1,420","Fullerton,CA","Farmers Branch,TX","12,000","New Wave International Cargo Inc, Hodgkins, IL",NaN
13:58,"1,452","Ontario,CA","Waco,TX","15,000","Transource Llc, Greenville, NC",NaN
13:56,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:51,"1,328","San Diego,CA","Ft Worth,TX","45,000","Coyote Logistics Llc, Alpharetta, GA",NaN
13:48,"1,438","Carson,CA","Irving,TX","25,000","Landstar Ranger, Lake Wales, FL",NaN
13:40,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:10,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
13:05,"1,527","Eastvale,CA","Mt Pleasant,TX","42,000","Echo Global Logistics Inc, Long Beach, CA",NaN
12:31,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
12:31,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN

In [228]:
df3 = pd.DataFrame(rows, columns=cols)
df3.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
14:33,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
14:18,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN
14:14,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
14:14,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
14:11,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
14:10,"1,328","San Diego,CA","Ft Worth,TX","45,000","Coyote Logistics Llc, Alpharetta, GA",NaN
14:09,"1,417","Fullerton,CA","Coppell,TX","40,000","Veritiv Operating Company, Norcross, GA",NaN
14:05,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
14:01,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
14:01,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
14:01,"1,438","Carson,CA","Irving,TX","30,000","Landstar Ranger Inc, Tampa, FL",NaN
14:01,"1,438","Carson,CA","Irving,TX","30,000","Landstar Ranger Inc, Tampa, FL",NaN
13:57,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:46,"1,428","Buena Park,CA","Dallas,TX","9,200","Sure Shot Logistics, Huntington Woods, MI",NaN
13:41,"\n\n\n\n 1,316","Vernon,CA","Humble,TX","40,000","Allen Lund Company, La Canada, CA",NaN
13:41,"1,435","Santa Fe Spgs,CA","Dallas,TX","16,000","Total Quality Logistics Inc, Milford, OH",NaN
13:40,"1,419","Vernon,CA","Hurst,TX","20,000","All State Association Inc, San Fernando, CA",NaN
13:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
13:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
13:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
13:33,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
13:31,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
13:30,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
12:32,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
12:32,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
11:04,"1,448","Long Beach,CA","Dallas,TX","20,000","All State Association Inc, San Fernando, CA",NaN

In [238]:
df4 = pd.DataFrame(rows, columns=cols)
df4.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
15:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
15:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
14:49,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
14:46,"\n\n\n\n 1,316","Vernon,CA","Humble,TX","40,000","Allen Lund Company, La Canada, CA",NaN
14:42,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
14:36,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
14:36,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
14:18,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN
14:11,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
14:10,"1,328","San Diego,CA","Ft Worth,TX","45,000","Coyote Logistics Llc, Alpharetta, GA",NaN
14:04,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
14:01,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
14:01,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
13:56,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:45,"1,428","Buena Park,CA","Dallas,TX","9,200","Sure Shot Logistics, Huntington Woods, MI",NaN
13:39,"1,419","Vernon,CA","Hurst,TX","20,000","All State Association Inc, San Fernando, CA",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN

In [248]:
df5 = pd.DataFrame(rows, columns=cols)
df5.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
15:31,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
15:16,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
14:49,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
14:46,"\n\n\n\n 1,316","Vernon,CA","Humble,TX","40,000","Allen Lund Company, La Canada, CA",NaN
14:42,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
14:36,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
14:36,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
14:18,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN
14:04,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:56,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:45,"1,428","Buena Park,CA","Dallas,TX","9,200","Sure Shot Logistics, Huntington Woods, MI",NaN
13:39,"1,419","Vernon,CA","Hurst,TX","20,000","All State Association Inc, San Fernando, CA",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
13:34,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN

In [261]:
df6 = pd.DataFrame(rows, columns=cols)
df6.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
16:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
16:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
16:00,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
15:51,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
15:51,"\n\n\n\n 1,316","Vernon,CA","Humble,TX","40,000","Allen Lund Company, La Canada, CA",NaN
15:41,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:30,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
15:16,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN

In [266]:
df61 = pd.DataFrame(rows, columns=cols)
df61.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
15:51,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
15:51,"\n\n\n\n 1,316","Vernon,CA","Humble,TX","40,000","Allen Lund Company, La Canada, CA",NaN
15:41,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:30,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
15:16,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
15:06,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
14:48,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
14:36,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
14:18,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN
14:04,"1,423","City Of Indus,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:56,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:45,"1,428","Buena Park,CA","Dallas,TX","9,200","Sure Shot Logistics, Huntington Woods, MI",NaN
13:39,"1,419","Vernon,CA","Hurst,TX","20,000","All State Association Inc, San Fernando, CA",NaN
12:31,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN

In [274]:
df7 = pd.DataFrame(rows, columns=cols)
df7.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
16:18,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
16:15,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
16:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
16:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
16:00,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
15:51,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
15:40,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:34,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:30,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
14:35,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
14:17,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN

In [287]:
df8 = pd.DataFrame(rows, columns=cols)
df8.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
16:57,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
16:48,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
16:47,"1,423","City Of Indus,CA","Dallas,TX","26,000","Freight Runner Inc, Chino, CA",NaN
16:43,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
16:18,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
16:13,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
16:13,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
16:02,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
15:54,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
15:38,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:38,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:38,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:38,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:38,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:37,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:37,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:33,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN

In [298]:
df9 = pd.DataFrame(rows, columns=cols)
df9.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
17:24,"1,423","City Of Indus,CA","Dallas,TX","26,000","Freight Runner Inc, Chino, CA",NaN
17:20,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
17:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
17:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
17:01,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
16:45,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
16:40,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
15:59,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
15:34,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:34,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:30,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN

In [309]:
df10 = pd.DataFrame(rows, columns=cols)
df10.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
18:00,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
17:59,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
17:59,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
17:51,"1,423","City Of Indus,CA","Dallas,TX","26,000","Freight Runner Inc, Chino, CA",NaN
17:50,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
17:20,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
17:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
17:10,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
17:01,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
16:40,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN

,miles,origin,dest,weight,shipper,time
posted,,,,,,
18:26,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
18:16,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:16,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:12,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
18:01,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
17:51,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
16:41,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [329]:
df12 = pd.DataFrame(rows, columns=cols)
df12.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
18:51,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
18:40,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
18:26,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
18:15,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:15,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:11,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
18:00,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:35,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [339]:
df13 = pd.DataFrame(rows, columns=cols)
df13.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
19:21,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
19:21,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
19:21,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:51,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
18:41,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
18:26,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
18:01,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
18:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
17:36,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [349]:
df14 = pd.DataFrame(rows, columns=cols)
df14.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
20:05,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
19:55,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
19:30,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
19:21,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
19:20,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
19:20,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
18:40,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [359]:
df15 = pd.DataFrame(rows, columns=cols)
df15.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
20:35,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
20:25,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
20:25,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
20:05,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
19:55,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
19:21,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
18:40,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
15:34,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN
14:17,"1,364","Mira Loma,CA","Ft Worth,TX","42,100","Arcbest Dedicated/Logistics & Distribution, Sp...",NaN
13:56,"1,440","Los Angeles,CA","Dallas,TX","41,800","R2 Logistics Inc, Dallas, TX",NaN
13:45,"1,428","Buena Park,CA","Dallas,TX","9,200","Sure Shot Logistics, Huntington Woods, MI",NaN
13:39,"1,419","Vernon,CA","Hurst,TX","20,000","All State Association Inc, San Fernando, CA",NaN
12:31,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN

In [370]:
df15 = pd.DataFrame(rows, columns=cols)
df15.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
21:01,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
20:46,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
20:42,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
20:36,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
20:26,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
20:26,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
20:06,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
20:01,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
20:01,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
19:41,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:41,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:41,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
16:56,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [383]:
df16 = pd.DataFrame(rows, columns=cols)
df16.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
21:30,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
21:30,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
21:00,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
20:45,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
20:41,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
20:35,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
20:05,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
20:00,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
19:40,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
16:55,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [396]:
df17 = pd.DataFrame(rows, columns=cols)
df17.set_index('posted')

,miles,origin,dest,weight,shipper,time
posted,,,,,,
22:01,"1,501","Oxnard,CA","Dallas,TX","38,000","Coyote Logistics Llc, Alpharetta, GA",NaN
22:01,"1,382","Moreno Valley,CA","Dallas,TX","40,000","Western Express Inc, Nashville, TN",NaN
22:01,"1,382","Moreno Valley,CA","Dallas,TX","9,672","Western Express Inc, Nashville, TN",NaN
21:52,"1,390","San Bernardino,CA","Dallas,TX",â€”,"Mid America Freight Logistics LLC, Fenton, MO",NaN
21:41,"1,390","San Bernardino,CA","Dallas,TX","19,000","JB Hunt Transport Services Inc, Lowell, AR",NaN
21:41,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
21:41,"1,303","Beaumont,CA","Coppell,TX","28,000","Schneider National Inc, Green Bay, WI",NaN
21:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
21:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
21:41,"1,303","Beaumont,CA","Coppell,TX","28,575","SCHNEIDER NATIONAL INC, Green Bay, WI",NaN
21:41,"1,359","Boron,CA","Dallas,TX","41,503","Bnsf Logistics Llc, Chicago, IL",NaN
21:31,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
21:31,"1,359","Boron,CA","Dallas,TX","41,000","Landstar Ranger, Houston, TX",NaN
20:46,"1,360","San Diego,CA","Lewisville,TX","25,000","PLS Logistics Services, Jacksonville, FL",NaN
20:06,"1,407","Fullerton,CA","Roanoke,TX","20,112","Uber Freight Llc, Chicago, IL",NaN
16:56,"1,402","Ontario,CA","Flower Mound,TX","45,000","Knight-Swift Logistics, Phoenix, AZ",NaN
15:35,"1,538","Ventura,CA","Terrell,TX","7,100","Pilot Truck Brokerage LLC, San Diego, CA",NaN

In [391]:
driver.find_element_by_id('search-new').click()
driver.find_element_by_id('searchform-search').click()

In [291]:
len(rows)

0

In [281]:
df.to_csv('df.csv')
df61.to_csv('df61.csv')
df17.to_csv('df17.csv')

In [390]:
df10.to_csv('df10.csv')
df12.to_csv('df12.csv')
df13.to_csv('df13.csv')
df14.to_csv('df14.csv')
df15.to_csv('df15.csv')
df16.to_csv('df16.csv')